create table if not exists clubes (
  id bigint generated by default as identity primary key,
  nome text not null,
  estado text,
  escudo_url text,
  created_at timestamptz default now()
);

create table if not exists campanhas_copa_brasil (
  id bigint generated by default as identity primary key,
  clube_id bigint references clubes(id),
  ano int not null,
  titulo text,
  jogos int default 0,
  gols_pro int default 0,
  gols_contra int default 0,
  created_at timestamptz default now()
);

create table if not exists jogadores_copa_brasil (
  id bigint generated by default as identity primary key,
  campanha_id bigint references campanhas_copa_brasil(id),
  nome text not null,
  posicoes text[] not null,
  overall int default 70,
  ataque int default 70,
  defesa int default 70,
  titular boolean default true,
  created_at timestamptz default now()
);

create table if not exists simulacoes_14x0 (
  id uuid primary key default gen_random_uuid(),
  nome_usuario text,
  escalacao jsonb not null,
  overall int,
  gols_pro int,
  gols_contra int,
  campeao boolean default false,
  pontos int default 0,
  created_at timestamptz default now()
);

alter table clubes enable row level security;
alter table campanhas_copa_brasil enable row level security;
alter table jogadores_copa_brasil enable row level security;
alter table simulacoes_14x0 enable row level security;

create policy "Leitura publica clubes" on clubes for select using (true);
create policy "Leitura publica campanhas" on campanhas_copa_brasil for select using (true);
create policy "Leitura publica jogadores" on jogadores_copa_brasil for select using (true);
create policy "Leitura publica simulacoes" on simulacoes_14x0 for select using (true);
create policy "Inserir simulacoes" on simulacoes_14x0 for insert with check (true);
